import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar/Navbar'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className={styles.body}>
      <Head>
        <title>Canchas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>

      <main className={styles.container}>
        <div className={styles.header}>
        <h3>
          JUGÁ AL FÚTBOL
          <br />

          SIEMPRE
        </h3>
        <h6>Explorá las canchas disponibles</h6>
        </div>
        <div className={styles.cards}>
        <p>Reservá tu cancha</p>
        <div className={styles.box}>
          <p>5 VS 5</p>
        </div>
        <div className={styles.box}>
          <p>7 VS 7</p>
        </div>
        <div className={styles.box}>
          <p>11 VS 11</p>
        </div>

        </div>
      </main>

<Footer/>
    </div>
  )
}
